modLoader = "javafml"
loaderVersion = "[33,)"
license = "GNU General Public License v3.0"
issueTrackerURL="https://github.com/zi-jing/CuckooLib/issues"

[[mods]]
  modId = "cuckoolib"
  version = "1.0.1"
  displayName = "CuckooLib"
  displayURL = "https://github.com/zi-jing/CuckooLib/tree/1.16"
  credits="Cuckoo Dev Team"
  authors = "zi_jing, Os-Ir, gonggongjohn, molybdenum, NathanGX"
  description = "The Cuckoo Commons Library"

  [[dependencies.cuckoolib]]
    modId = "forge"
    mandatory = true
    versionRange = "[33,)"
    ordering = "NONE"
    side = "BOTH"

  [[dependencies.cuckoolib]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.2,)"
    ordering = "NONE"
    side = "BOTH"
